### ISSUE TITLE
add a **see also** section to readme

### ISSUE THREAD

**Issue by japhir** [mdaeron/D47crunch#11]
With the recent release of David Bajnai's [`isogeochem`](https://github.com/davidbajnai/isogeochem), people looking for clumped-related processing code might be getting a bit lost in the woods when searching github. It would be nice to add a short description to each of our README sections linking to each other's projects, specifying how the projects differ from each other. What do you think?

I've added the following short sentence to my R package [`clumpedr`](https://github.com/isoverse/clumpedr/tree/dev)'s dev branch:
> - [`D47crunch`](https://github.com/mdaeron/D47crunch) is the Python processing code to process clumped data from δ47 values. It features a pooled regression for the empirical transfer function and many other features.

are you happy with the description?

**Comment by mdaeron** [comment]
> With the recent release of David Bajnai's [`isogeochem`](https://github.com/davidbajnai/isogeochem), people looking for clumped-related processing code might be getting a bit lost in the woods when searching github. It would be nice to add a short description to each of our README sections linking to each other's projects, specifying how the projects differ from each other. What do you think?

Every project linking to every other project will scale poorly, won't it? I'd suggest something like "Awesome clumpy resources" (or some better name) inspired by other "Awesome" lists (e.g., [here](https://github.com/mcauser/awesome-micropython)).

> I've added the following short sentence to my R package [`clumpedr`](https://github.com/isoverse/clumpedr/tree/dev)'s dev branch:
> 
> > * [`D47crunch`](https://github.com/mdaeron/D47crunch) is the Python processing code to process clumped data from δ47 values. It features a pooled regression for the empirical transfer function and many other features.
> 
> are you happy with the description?

Sure, thanks. I'd just suggest mentioning that it does Δ48 as well, since it is not obvious from the name.

**Comment by mdaeron** [comment]
> Every project linking to every other project will scale poorly, won't it? I'd suggest something like "Awesome clumpy resources" (or some better name) inspired by other "Awesome" lists (e.g., [here](https://github.com/mcauser/awesome-micropython)).

Based on this issue I just made this: [clumpynomicon](https://github.com/mdaeron/clumpynomicon). Perhaps it'll catch on.
