### ISSUE TITLE
missing depency: rich?

### ISSUE THREAD

**Issue by timpol** [mdaeron/D47crunch#16]
Hi Mathieu, 

I just installed the latest version of D47crunch in a new virtual env and encountered the following error when importing ```D47crunch```:

```
AttributeError: module 'typer' has no attribute 'rich_utils'
```

It seems to have been resolved by installing the ```rich``` package. 

Should this be added as a dependency in the ```.toml``` file?

**Comment by mdaeron** [comment]
Good catch, thanks. Corrected in v2.3.2.
