### ISSUE TITLE
Output temperature in Table of Samples?

### ISSUE THREAD

**Issue by timpol** [mdaeron/D47crunch#18]
Would it be possible / make any sense for `D47data.table_of_samples()` to accept temperature calibration constants as optional arguments and output D47 temperature in the Table of Samples?

**Comment by mdaeron** [comment]
Impeccable timing!

The brand-new [D47calib](https://mdaeron.github.io/D47calib/#22-integration-with-d47crunchhttpsgithubcommdaerond47crunch) library may fit your needs. Repo [here](https://github.com/mdaeron/D47calib).

**Comment by timpol** [comment]
This is somewhat more sophisticated than what I was envisaging... Looks fantastic!
